package com.skyblu.configuration

import android.Manifest


const val APP_NAME_STRING = "Skyblu"
const val ID_STRING = "ID"
const val EMAIL_STRING = "Email"
const val TITLE_STRING = "Title"
const val DROPZONE_STRING = "Dropzone"
const val AIRCRAFT_STRING = "Aircraft"
const val EQUIPMENT_STRING = "Equipment"
const val DESCRIPTION_STRING = "Description"
const val EDIT_JUMP_STRING = "Edit Skydive"
const val UNKNOWN_USER_STRING = "Unknown User"
const val SPEEDS_STRING = "Speeds"
const val MAX_VERTICAL_SPEED_STRING = "Maximum Vertical Speed"
const val AVERAGE_GROUND_SPEED_STRING = "Average Ground Speed"
const val AVERAGE_VERTICAL_SPEED_STRING = "Average Vertical Speed"
const val MAX_GROUND_SPEED_STRING = "Max Ground Speed"
const val MPS_UNIT_STRING = "m/s"
const val M_UNIT_STRING = "m"
const val FT_UNIT_STRING = "ft"
const val TWO_DP_FORMAT_STRING = "%.2f"
const val DP_FORMAT_STRING = "%.1f"
const val EXIT_ALTITUDE_STRING = "Exit Altitude"
const val OPENING_ALTITUDE_STRING = "Opening Altitude"
const val DISTANCES_STRING = "Distances"
const val ALTITUDES_STRING = "Altitudes"
const val JUMP_DETAILS_STRING = "Skydive Details"
const val FREEFALL_STRING = "Freefall"
const val CANOPY_STRING = "Canopy"
const val UNKNOWN_STRING = "Unknown"
const val START_TRACKING_STRING = "Start Tracking"
const val STOP_TRACKING_STRING = "Stop Tracking"
const val PASSWORD_STRING = "Password"
const val CONFIRM_PASSWORD_STRING = "Confirm Password"
const val WELCOME_MESSAGE_STRING = "Welcome to $APP_NAME_STRING"
const val LOGIN_TO_APP_STRING = "Login to $APP_NAME_STRING"
const val DONT_HAVE_ACCOUNT_STRING = "Don't have an account? Create Account"
const val ACCOUNT_SETTINGS_STRING = "Account Settings"
const val IMAGE_REFERENCE_STRING = "image/*"
const val USERNAME_STRING = "Username"
const val BIO_STRING = "Bio String"
const val TRACKING_SETTINGS_STRING = "Tracking Settings"
const val PROFILE_STRING = "Profile"
const val HOME_STRING = "Home"
const val VERTICAL_DISTANCE_TRAVELLED_STRING = "Vertical Distance Travelled"
const val GROUND_DISTANCE_TRAVELLED_STRING = "ground Distance Travelled"
const val LOADING_STRING = "Loading"
const val PERMISSIONS = Manifest.permission.ACCESS_FINE_LOCATION
const val JUMPS_COLLECTION = "skydives"
const val USERS_COLLECTION = "users"
const val DATAPOINTS_COLLECTION = "datapoints"
const val JUMP_NUMBER_STRING = "Jump Number"
val JUMP_NUMBER_RANGE = 1..10000
const val LICENCE_STRING = "Licence"
const val TOTAL_JUMPS_STRING = "Jumps"
const val ALTITUDE_THRESHOLD_STRING = "Altitude Threshold"
const val GROUNDSPEED_THRESHOLD_STRING = "Groundspeed Threshold"
const val VERTICAL_SPEED_THRESHOLD_STRING = "Vertical Speed Threshold"
const val LOCATION_THRESHOLD_INT = 0.1
const val ALTITUDE_THRESHOLD_INT = 0.1



